Activity.create!([
  {name: "Bouldering"},
  {name: "Multi-Ptich Climbing"},
  {name: "Sport Climbing"},
  {name: "Alpine Climbing"},
  {name: "Trad Climbing"}
])
[
  {title: "Buttermilk Boulders", description: "The scenic and awe-inspiring Buttermilk Country has long been one of California's premier bouldering destinations with a long history of ground-breaking ascents and some of the proudest, boldest, and most aesthetic lines in the world. These massive glacial erratic boulders sit in the foothills of the Sierra Nevada under an impressive backdrop of high peaks just a mere four miles to the west. Granite-like quartz monzonite makes up the boulders featuring sweeping blank faces, polished patina crimps/plates and sharp slopers and edges. Fingers tend to get torn up quickly on the large grain so bring tape if your callouses aren't sufficient.", user_id: 1, lat: 37.2943766, lng: -118.6101148, location_name: "Buttermilk Country"},
  {title: "Happy Bouldering", description: "The Happy Boulders offer highly concentrated world-class volcanic bouldering with hundreds of worthy problems ranging from simple to impossible. The rock, which looks brittle and crumbly with a quick glance is surprisingly bomber volcanic Bishop Tuff, just be weary on high top-outs that may not see much traffic. The boulders found here offer faces that test every technique - most notably is the abundance of finger pockets which are found everywhere. You'll also find steep, gymnastic juggy overhangs and crimpy faces, as well as low traverses and unlimited eliminates and link-ups. Cracks of wide ranges can be found on the rim along with easy and scary highballing... it's all here. The landings are flat, the boulders are jam-packed, and everyone in your posse will find what they're looking for. ", user_id: 1, lat: 37.413638, lng: -118.447648, location_name: "Happy Boulders"},
  {title: "Mt. Whitney East Buttress ", description: "The premier moderate route in the Whitney Area. 4 mile approach up to Iceberg late at 12,2000 ft. Camp here for easy access to the east Buttress. 12 amazing pitches brings your through moderate terrain that's not hard and amazingly fun to climb on. Stunning views of the Owens River Valley. Tallest peak in the lower 48! Go bag it! ", user_id: 1, lat: 36.5784991, lng: -118.29226, location_name: "Mount Whitney"},
  {title: "Mt. Emerson Free Solo! ", description: "This is a relatively high and isolated mountain which commands an excellent view. The mountain was named by John Muir after writer Ralph Waldo Emerson! Mount Emerson is found between Piute Pass and Mount Humphreys. Its granite is in sharp contrast to the reddish rock of the Piute Crags. ", user_id: 1, lat: 37.2424336, lng: -118.65428, location_name: "Mount Emerson"},
  {title: "Tramway Bouldering", description: "The Tramway - so named due to most climbers using the Palm Springs Aerial Tramway to reach this bouldering area. The granite boulders here are scattered not too far from the Tramway station near the peak of Mt San Jacinto. \nThe climbing style can be best described as \"steep\". Small hold and high friction are the norm, especially during the winter and fall. Some of the best bouldering in the area. Bring lots of skin. ", user_id: 2, lat: 33.837064, lng: -116.614106, location_name: "Palm Springs Aerial Tramway"},
  {title: "Black Mountain Bouldering", description: "A premier bouldering locale of southern california, the granite boulders call out to any climber who visits this area. A variety of boulder problems are found, both in terms of steepness and grades. Located at 7500 ft, bouldering here is in a beautiful mountain setting - pine trees are as plentiful as the boulders are. \n\nMost newcomers to Black Mountain quickly notice two things: 1) the problems here are often tall and off-the-deck 2) the ratings are HARD for the grade. Fear not - many of the most visible problems are indeed tall (20+ feet in Boulder Basin), but shorter problems can be found if one looks close enough. As for the grades, I'd suggest leaving your egos at home... ", user_id: 2, lat: 33.8241848, lng: -116.757518, location_name: "Black Mountain"},
  {title: "Joshua Tree Bouldering", description: "I think everyone associates Joshua Tree Rock Climbing with bold and scary rope climbing. But the bouldering here is awesome. There are boulders scattered all over the park with some of the west coast's best climbing. With everything from cracks, highballs, and no hold faces, this place has it all. Not to be missed are the ultra clear skies that make for some fantastic star gazing. Check this place out. ", user_id: 2, lat: 33.873415, lng: -115.900992, location_name: "Joshua Tree National Park"},
  {title: "Way Lake Bouldering", description: "This bouldering venue has a distinctly Alpine flavor. The granite is dark much like Colorado granite. The style favors steep roofs and small hold. The setting could not be more gorgeous. You're nestled high above Mammoth and surrounded by high alpine lakes. This is a hidden gem work checking out. ", user_id: 2, lat: 37.5835117, lng: -118.9973439, location_name: "Way Lake"},
  {title: "Riverside Quarry Sport Climbing ", description: "The majority of the Quarry is west facing, so the seasons dictate when is the best time to climb. In the summer you can climb to noon, in the winter climb in the Agony Arch area in the morning and the rest of the crag in the afternoon. When it is really windy a few climbs in Slab City are protected. This is a popular area for dirt bikers; on the weekends it can get really busy and noisy. There are so many climbs here that crowds are sparse. \n\nThis place is a great place to spend an afternoon, but due to its close proximity to Riverside and other surrounding cities, there is a lot of trash, junked cars, and random other pieces of junk that no one wants anymore. If you are looking for a beautiful, quiet place to climb, this is definitely not it. If you are looking for an afternoon of fun climbing on good rock this is your ticket.", user_id: 4, lat: 34.016889, lng: -117.416607, location_name: "Riverside Quarry"},
  {title: "Holcomb Valley Sport Climbing", description: "Although the elevation of the Holcomb Valley Pinnacles (HVP) ranges between 7400-7600 feet it's not just a summer climbing area, with good climbing available all year-round depending upon the severity of the winter. Summers can sometimes be hot, making those shady climbs all the more attractive, while early and late season climbing can be ideal with relatively few climbers and few distractions but the sound of the wind in the pines. \n\nThe rock at the Pinnacles is a heavily-featured granite that ranges in quality from excellent to fair with the majority of it being quite goo", user_id: 4, lat: 34.3072273, lng: -116.9275337, location_name: "Holcomb Valley"},
  {title: "New Jack City Sport Climbing", description: "New Jack City (NJC), also known as Sawtooth Canyon, is a sport climbing destination near Barstow, CA. With more than 350 sport climbs ranging from 5.6 - 5.13 scattered across the high desert, New Jack City offers something for climbers of all abilities. The rock is an unusual form of metamorphic rock of volcanic origin, offering often tricky and thought-provoking sequences and moves on huecos, pockets, edges, jugs, underclings, and crimps. The climbing is typically steep and diverse, requiring both strength and technique. Located in the high desert the climbing season runs from October through May", user_id: 4, lat: 34.680988, lng: -116.966307, location_name: "New Jack City"},
  {title: "Malibu Sport Climbing", description: "Nestled in the foothills of the Santa Monica mountains, this popular park is home to a lot of use. Hikers, swimmers, bikers, and climbers all share the area. Climbing is confined to a horseshoe shaped canyon with a small stream. The climbing here is fun with lots of routes for everyone. ", user_id: 8, lat: 34.105077, lng: -118.731519, location_name: "Malibu Creek State Park"},
  {title: "Echo Cliffs Sport Climbing", description: "Echo Cliffs has become one of the premier sport climbing venues in Southern California and hosts nearly 200 routes. Echo Cliff offers many faces that feature pockets and blocky holds on vertical to overhanging rock in a beautiful, typically sunny setting", user_id: 8, lat: 34.125052, lng: -118.927297, location_name: "Echo Cliffs"},
  {title: "Mt. Russell Fishook Arete", description: "At 14,088 ft (4,294 m), Mt. Russell is the 7th highest peak in California, and one of 15 above 14,000' in the state. Though overshadowed by it's taller neighbor Mt. Whitney, getting to the summit of Mt. Russell is far more challenging. The easiest route is tough and steep 4th class ridge traversing while everything else on the west face is 5.9+ or harder. But the summit is spectacular. Some of the best in the Sierra. ", user_id: 6, lat: 36.5899349, lng: -118.2906469, location_name: "Mount Russell"},
  {title: "Charlotte Dome", description: "Beautiful dome in the Sierra backcountry, this place is guarded by a 12 mile one way approach. Plan to spend an entire day just getting there. But the isolation and views are so worth the trek. Camping puts you right below the back of the dome on a magical plateau overlooking the confluence of Charlotte and Bubbs Creek. \nThe climbing is moderate and spectacular with more than one pitch you'll smile when thinking about. ", user_id: 6, lat: 36.7824365, lng: -118.4806533, location_name: "Charlotte Dome"},
  {title: "Matthes Crest", description: "Matthes Crest is an extremely long knife edge fin that cuts across a spectacular part of Tuolumne. It is sought after for its length, moderate grade, and the unique element of a huge fin traverse in an awe inspiring area of the country. It is most widely known for its traverse, but many other routes exist on both sides. \n\nThe Matthes Crest Traverse is a true 5 star classic route characterized by mostly 4th class climbing with the occasional fifth class section. With immense exposure on many sections it offers a rare experience to enjoy such a long moderate route in an idyllic setting. Located in a region completely invisible to tourists or road traffic, it gives the true feel of a backcountry alpine climb.", user_id: 6, lat: 37.823259, lng: -119.3973791, location_name: "Matthes Crest"},
  {title: "Cathedral Peak ", description: "One of the most stunning peaks in Yosemite, Cathedral is blessed with some great moderate climbing. The approach takes about an hour and is long enough from the road and hiking trails to give you a little peace (often to be shared with many climbers - start early). \n\nThe summit is a small block big enough for a couple people to squeeze on. Their might be bolts on the top, but usually not. Downclimbing off the summit block can be scary, but John Muir did it in 1869, so you can too. ", user_id: 6, lat: 37.8478592, lng: -119.4058774, location_name: "Cathedral Peak"},
  {title: "Needles Climbing", description: "Breathtaking and shrouded in mystery, the Needles are a series of enormous granite spires that stand watch atop a narrow ridge that sits high over the Kern River in Sequoia National Forest. This is a climber's paradise: perfect rock, beautiful scenery, minimal crowds, and adventure in abundance. ", user_id: 5, lat: 36.1093895, lng: -118.4845316, location_name: "The Needles"},
  {title: "Joshua Tree Trad Climbing", description: "Joshua Tree is a magical wonderland of rocks. The landscape is alien and harsh, but the climbing is world class. Joshua Tree is a world famous area with thousands of routes. Long popular as a winter destination, it's appeal has only grown throughout the years as climbers of all abilities have discovered the mild temperatures, grippy rock and surreal landscape which make it a must visit area on any climber's list. ", user_id: 5, lat: 34.017405, lng: -116.16162, location_name: "Hidden Valley Campground"},
  {title: "Tahquitz Multi-pitch ", description: "Overlooking the quaint mountain town of Idyllwild, Tahquitz is the obvious granite monolith high up on the hillside. The climbing is clean and has routes for all abilities. The rock can be lose in areas that are not well traveled, but this area is the brith place of the modern climbing grading system. Yosemite's pioneers were the first to explore this area and as such it has a heavy history. As the premiere mulit-pitch meca of Southern California, the place is not to be missed! ", user_id: 5, lat: 33.7558539, lng: -116.6761288, location_name: "Tahquitz Peak"},
  {title: "Castle Rock Climbing", description: "Surrounding Castle Rock State Park is one of the larger climbing regions in the area, hosting a variety of sport, trad, bouldering and top rope problems. \n\nThe rock is mostly sandstone, making it fairly easy on the hands and dynos quite slap happy. \n\nAccess into the main park will cost you a couple of dollars, but that shouldn't deter you. If money is a concern, you can also park outside the main area and walk into the park. \n\nThe bouldering at Castle Rock is some of the best in the state, if not the whole western U.S. \n", user_id: 7, lat: 37.230693, lng: -122.095532, location_name: "Castle Rock State Park"},
  {title: "Lover's Leap", description: "This area is an excellent 250 to nearly 600 foot tall chunk of mostly vertical granite, containing hundreds of cracks crisscrossed with thousands of horizontal dikes. These dikes are key to reducing what would otherwise be very steep and difficult traditional routes, into routes with good rests and abundant holds, resulting in an area with relatively moderate grades. You will find over 250 developed routes that range from low bouldering traverses to 4 pitches tall. Some routes are bolt protected, but most of the sport climbing is 5.10+ YDS or harder, as the abundance of traditionally protected routes in close proximity to each other discourages squeezing in a bunch of moderate sport face climbing. All of the routes demand less than 20 minutes to \"hike\" into, as the entrance path is part of the pioneer trail, and therefore excellently maintained and quite wide", user_id: 7, lat: 38.799444, lng: -120.135556, location_name: "Lover's Leap"},
  {title: "Berkeley Bouldering ", description: "Inner city bouldering at its best. This area is located inside the city of Berkeley, and elimination problems are the rule. Indian Rock is a locals' favorite because of its easy approach and accessible setting. It can be busy after 5 and on weekends, but if you've got a couple of hours to spare, it's only a few miles from the Berkeley campus, and set in a nice upscale neighborhood. \n\nRock is mostly smooth, but there is some sharper stuff on the upper area of the rock. ", user_id: 7, lat: 37.892298, lng: -122.272655, location_name: "Indian Rock Park"},
  {title: "Jailhouse Rock", description: "Jailhouse offers steep, blocky, volcanic sport climbing on basalt. Routes are in the shade in the morning, and in the sun in the afternoon. The low elevation crag is best in the winter (although many routes seep given California's winter rains) or early spring/late fall. It's much too hot in the summer unless you are a reptile. The quality climbing here starts at 12d and currently goes to 14+, although there are some limited easier routes. The two easiest routes at the cliff are frequently closed for nesting raptors. The easiest route is 11d, but there are only 3 routes easier than 12b. Many routes, particularly the many extensions, require a 70m rope. Most will find kneepads and well-developed stamina helpful", user_id: 7, lat: 37.9038151, lng: -120.5632563, location_name: "Shotgun Creek"},
  {title: "SF Beach Climbing", description: "Mickey's Beach offers some of the toughest sport climbing in the area, along with some interesting bouldering. Almost all climbs are on the beach, and some are tide dependant. The area can be quite windy, making some of the balancy moves more interesting. Climbs offered range from beginning to expert. \n\nThe whole area is free. \n\nA brief bit of history tells that the bouldering area west of the main rock was once a part of the hillside, and in a huge storm in 1986 it fell into the surf as one large chunk. Seven days later, the rock split into pieces, directly in front of an unsuspecting picnicing couple. \n\nThe main rock also had some storm trouble. In 1993 a huge storm knocked several classic climbs off the main rock and into the ocean, including a classic 5.12 finger crack known as Mickey's crack. A word of caution for people who travel to Mickey's beach, which is that it's a spot frequented by a rather large group of nudists, so if that bothers you, you should probably climb some place else. ", user_id: 3, lat: 37.891688, lng: -122.635279, location_name: "Stinson Beach Boulders"},
  {title: "Mount St. Helna Sport Climbing", description: "Overlooking Napa Valley, Mount St. Helena is about the most scenic climbing in the Bay Area. If you're willing to hike there's a ton of trad climbing in the area, but thus far, I've been too lazy to get anywhere but the three sport climbing areas. The rock is volcanic in origin, and ranges widely in forms, thus specific descriptions will be saved for each crag. Recently, Aron and I discovered that Forrest Shute has been hiding in the Los Angeles area. He mentioned that he had about half of all the first ascents on the Mountain, and that there's a lot more climbing past the Far Side than just that available in guidebooks. Hopefully, we'll be able to share a little more of his wisdom in the future.", user_id: 3, lat: 38.6693509, lng: -122.6333189, location_name: "Mount Saint Helena"},
  {title: "Owens River Climbing", description: "The Owens River Gorge is California's most concentrated sport-climbing area. It is really a year-round crag, although summers can be a bit hot. There are many moderate sport climbs in the sub 5.10 range, but the best gorge climbs seem to be in the 5.10-5.11 range. The climbing is on volcanic tuff and features edges, pockets and cracks. Most of the climbing is close to vertical but there are some steep lines as well, namely at the Eldorado Roof and the Dilithium Crystal. Most climbs, whether face, crack, corner, even off-width and chimney, are fully sport bolted. There are some good trad lines, but sport climbing is why you're here. ", user_id: 3, lat: 37.509096, lng: -118.575257, location_name: "Owens River Gorge"}
].each do |adventure| 
  a = Adventure.new(adventure)
  a.save(validate: false)
end

AdventureActivity.create!([
  {adventure_id: 1, activity_id: 1},
  {adventure_id: 2, activity_id: 1},
  {adventure_id: 3, activity_id: 2},
  {adventure_id: 3, activity_id: 4},
  {adventure_id: 3, activity_id: 5},
  {adventure_id: 4, activity_id: 2},
  {adventure_id: 4, activity_id: 4},
  {adventure_id: 5, activity_id: 1},
  {adventure_id: 6, activity_id: 1},
  {adventure_id: 7, activity_id: 1},
  {adventure_id: 8, activity_id: 1},
  {adventure_id: 9, activity_id: 3},
  {adventure_id: 10, activity_id: 3},
  {adventure_id: 11, activity_id: 3},
  {adventure_id: 12, activity_id: 3},
  {adventure_id: 13, activity_id: 3},
  {adventure_id: 14, activity_id: 2},
  {adventure_id: 14, activity_id: 4},
  {adventure_id: 14, activity_id: 5},
  {adventure_id: 15, activity_id: 2},
  {adventure_id: 15, activity_id: 4},
  {adventure_id: 15, activity_id: 5},
  {adventure_id: 16, activity_id: 2},
  {adventure_id: 16, activity_id: 4},
  {adventure_id: 16, activity_id: 5},
  {adventure_id: 17, activity_id: 2},
  {adventure_id: 17, activity_id: 4},
  {adventure_id: 17, activity_id: 5},
  {adventure_id: 18, activity_id: 2},
  {adventure_id: 18, activity_id: 5},
  {adventure_id: 19, activity_id: 5},
  {adventure_id: 20, activity_id: 2},
  {adventure_id: 20, activity_id: 5},
  {adventure_id: 21, activity_id: 1},
  {adventure_id: 22, activity_id: 2},
  {adventure_id: 22, activity_id: 5},
  {adventure_id: 23, activity_id: 1},
  {adventure_id: 24, activity_id: 3},
  {adventure_id: 25, activity_id: 1},
  {adventure_id: 26, activity_id: 3},
  {adventure_id: 26, activity_id: 5},
  {adventure_id: 27, activity_id: 3}
])
AdventureFeature.create!([
  {adventure_id: 1, feature_id: 1},
  {adventure_id: 1, feature_id: 2},
  {adventure_id: 1, feature_id: 3},
  {adventure_id: 2, feature_id: 4},
  {adventure_id: 2, feature_id: 5},
  {adventure_id: 3, feature_id: 2},
  {adventure_id: 3, feature_id: 3},
  {adventure_id: 3, feature_id: 6},
  {adventure_id: 3, feature_id: 7},
  {adventure_id: 4, feature_id: 6},
  {adventure_id: 4, feature_id: 7},
  {adventure_id: 4, feature_id: 8},
  {adventure_id: 5, feature_id: 2},
  {adventure_id: 5, feature_id: 6},
  {adventure_id: 5, feature_id: 9},
  {adventure_id: 6, feature_id: 1},
  {adventure_id: 6, feature_id: 2},
  {adventure_id: 6, feature_id: 3},
  {adventure_id: 6, feature_id: 5},
  {adventure_id: 6, feature_id: 6},
  {adventure_id: 6, feature_id: 7},
  {adventure_id: 7, feature_id: 1},
  {adventure_id: 7, feature_id: 2},
  {adventure_id: 7, feature_id: 3},
  {adventure_id: 7, feature_id: 10},
  {adventure_id: 7, feature_id: 11},
  {adventure_id: 8, feature_id: 2},
  {adventure_id: 8, feature_id: 7},
  {adventure_id: 8, feature_id: 9},
  {adventure_id: 9, feature_id: 2},
  {adventure_id: 9, feature_id: 12},
  {adventure_id: 9, feature_id: 13},
  {adventure_id: 9, feature_id: 14},
  {adventure_id: 10, feature_id: 2},
  {adventure_id: 10, feature_id: 3},
  {adventure_id: 10, feature_id: 6},
  {adventure_id: 10, feature_id: 7},
  {adventure_id: 11, feature_id: 4},
  {adventure_id: 11, feature_id: 7},
  {adventure_id: 11, feature_id: 11},
  {adventure_id: 12, feature_id: 4},
  {adventure_id: 12, feature_id: 14},
  {adventure_id: 12, feature_id: 15},
  {adventure_id: 13, feature_id: 4},
  {adventure_id: 13, feature_id: 5},
  {adventure_id: 13, feature_id: 7},
  {adventure_id: 14, feature_id: 2},
  {adventure_id: 14, feature_id: 6},
  {adventure_id: 14, feature_id: 7},
  {adventure_id: 15, feature_id: 2},
  {adventure_id: 15, feature_id: 6},
  {adventure_id: 15, feature_id: 7},
  {adventure_id: 15, feature_id: 16},
  {adventure_id: 16, feature_id: 2},
  {adventure_id: 16, feature_id: 6},
  {adventure_id: 16, feature_id: 7},
  {adventure_id: 16, feature_id: 8},
  {adventure_id: 16, feature_id: 16},
  {adventure_id: 17, feature_id: 2},
  {adventure_id: 17, feature_id: 6},
  {adventure_id: 17, feature_id: 7},
  {adventure_id: 17, feature_id: 10},
  {adventure_id: 18, feature_id: 2},
  {adventure_id: 18, feature_id: 3},
  {adventure_id: 18, feature_id: 7},
  {adventure_id: 18, feature_id: 10},
  {adventure_id: 18, feature_id: 16},
  {adventure_id: 19, feature_id: 1},
  {adventure_id: 19, feature_id: 2},
  {adventure_id: 19, feature_id: 3},
  {adventure_id: 19, feature_id: 7},
  {adventure_id: 19, feature_id: 10},
  {adventure_id: 19, feature_id: 17},
  {adventure_id: 20, feature_id: 2},
  {adventure_id: 20, feature_id: 7},
  {adventure_id: 20, feature_id: 10},
  {adventure_id: 20, feature_id: 13},
  {adventure_id: 21, feature_id: 5},
  {adventure_id: 21, feature_id: 14},
  {adventure_id: 21, feature_id: 18},
  {adventure_id: 22, feature_id: 2},
  {adventure_id: 22, feature_id: 7},
  {adventure_id: 22, feature_id: 19},
  {adventure_id: 23, feature_id: 5},
  {adventure_id: 23, feature_id: 14},
  {adventure_id: 23, feature_id: 18},
  {adventure_id: 24, feature_id: 4},
  {adventure_id: 24, feature_id: 9},
  {adventure_id: 24, feature_id: 13},
  {adventure_id: 24, feature_id: 20},
  {adventure_id: 25, feature_id: 9},
  {adventure_id: 25, feature_id: 12},
  {adventure_id: 25, feature_id: 18},
  {adventure_id: 25, feature_id: 21},
  {adventure_id: 26, feature_id: 4},
  {adventure_id: 26, feature_id: 7},
  {adventure_id: 26, feature_id: 17},
  {adventure_id: 26, feature_id: 19},
  {adventure_id: 27, feature_id: 3},
  {adventure_id: 27, feature_id: 4},
  {adventure_id: 27, feature_id: 7},
  {adventure_id: 27, feature_id: 9},
  {adventure_id: 27, feature_id: 10},
  {adventure_id: 27, feature_id: 20}
])
AdventureLike.create!([
  {adventure_id: 4, user_id: 4},
  {adventure_id: 2, user_id: 4},
  {adventure_id: 1, user_id: 4},
  {adventure_id: 10, user_id: 8},
  {adventure_id: 9, user_id: 8},
  {adventure_id: 3, user_id: 6},
  {adventure_id: 4, user_id: 6},
  {adventure_id: 3, user_id: 5},
  {adventure_id: 15, user_id: 5},
  {adventure_id: 16, user_id: 5},
  {adventure_id: 4, user_id: 5},
  {adventure_id: 6, user_id: 3},
  {adventure_id: 10, user_id: 3},
  {adventure_id: 8, user_id: 3},
  {adventure_id: 7, user_id: 3},
  {adventure_id: 27, user_id: 1},
  {adventure_id: 17, user_id: 1},
  {adventure_id: 2, user_id: 2},
  {adventure_id: 1, user_id: 2},
  {adventure_id: 21, user_id: 2},
  {adventure_id: 23, user_id: 2},
  {adventure_id: 25, user_id: 2},
  {adventure_id: 20, user_id: 6},
  {adventure_id: 19, user_id: 6}
])
AdventureList.create!([
  {adventure_id: 1, list_id: 1},
  {adventure_id: 2, list_id: 1},
  {adventure_id: 3, list_id: 2},
  {adventure_id: 4, list_id: 2},
  {adventure_id: 5, list_id: 3},
  {adventure_id: 7, list_id: 3},
  {adventure_id: 6, list_id: 3},
  {adventure_id: 12, list_id: 5},
  {adventure_id: 13, list_id: 5},
  {adventure_id: 9, list_id: 6},
  {adventure_id: 11, list_id: 6},
  {adventure_id: 10, list_id: 6},
  {adventure_id: 14, list_id: 8},
  {adventure_id: 15, list_id: 8},
  {adventure_id: 18, list_id: 9},
  {adventure_id: 20, list_id: 9},
  {adventure_id: 19, list_id: 9},
  {adventure_id: 22, list_id: 10},
  {adventure_id: 17, list_id: 10},
  {adventure_id: 16, list_id: 10},
  {adventure_id: 21, list_id: 11},
  {adventure_id: 23, list_id: 11},
  {adventure_id: 25, list_id: 11}
])
Feature.create!([
  {name: "Highballs"},
  {name: "Granite"},
  {name: "Great Camping"},
  {name: "Volcanic"},
  {name: "Gymnastic"},
  {name: "High Elevation "},
  {name: "Amazing Views"},
  {name: "Free Solo"},
  {name: "Steep Rock"},
  {name: "Slab"},
  {name: "Great Star Gazing"},
  {name: "Dirty"},
  {name: "Loose Rock"},
  {name: "Urban"},
  {name: "Swimming Hole"},
  {name: "Remote"},
  {name: "Sharp Rock"},
  {name: "Sandstone"},
  {name: "Crack Climbing"},
  {name: "Hard Climbing"},
  {name: "Ocean Front"}
])
Follow.create!([
  {followee_id: 1, follower_id: 5},
  {followee_id: 4, follower_id: 5},
  {followee_id: 6, follower_id: 3},
  {followee_id: 5, follower_id: 3},
  {followee_id: 3, follower_id: 2}
])
[
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445734567/cbjbzdngey2vz8lvfqkf.jpg", imagable_id: 1, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445734570/sla5uytsb1cagayosiii.jpg", imagable_id: 1, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445734575/zpxd4jaee2xnjs05fros.jpg", imagable_id: 1, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445734580/wfykrknab11a0crvrzv4.jpg", imagable_id: 1, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445734584/onymcwhosz7aty8ys4cm.jpg", imagable_id: 1, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445735436/laxlcfctm49ymtizjygy.jpg", imagable_id: 2, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445735439/pabbaipnj2fkz5hxsrjk.jpg", imagable_id: 2, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445735443/lad0j7wzvumwbvevslqj.jpg", imagable_id: 2, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445735448/toofizrxuk8y7wll3qma.jpg", imagable_id: 2, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445837314/mwhaiinuwxdnf393kmtl.jpg", imagable_id: 1, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445837367/x9fngqeiapzth6kac4di.jpg", imagable_id: 2, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445837415/fv4b3xtmpx1fvlze2wya.jpg", imagable_id: 3, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445837485/cvakuex53e92cajywbsr.jpg", imagable_id: 4, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445837648/jaa1fyatp54eia1i9c1j.jpg", imagable_id: 5, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841284/typ4pabiao5cyqiye9yj.jpg", imagable_id: 7, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841287/dbjtt8nodchlliypludh.jpg", imagable_id: 7, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445838098/ekc3cbsot0jxgsr5hjzt.jpg", imagable_id: 6, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445838292/xjvljeq1isyzm4b6jdxx.jpg", imagable_id: 7, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445838407/d9my6axyxbu6jymjxf84.jpg", imagable_id: 8, imagable_type: "User"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445839319/fnrrof2evfbobk5u47sr.jpg", imagable_id: 3, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445839323/litxh1keelkloybh5khp.jpg", imagable_id: 3, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445839338/lkzbrqfvvsbupaf3e8k1.jpg", imagable_id: 3, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445839410/q8o5ful5itouqhuudmma.jpg", imagable_id: 3, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445839480/ca5yip9n1x5xpciqadui.jpg", imagable_id: 3, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840000/tiobeubrujcaftxdr2we.jpg", imagable_id: 4, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840017/jj6hun9opefz82ejhirm.jpg", imagable_id: 4, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840026/ysefdxdtvglrn9wxuflw.jpg", imagable_id: 4, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840034/jsny6n1hbzhedg5m9ufx.jpg", imagable_id: 4, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840043/nsdjtwuxtspkxyy7oe0i.jpg", imagable_id: 4, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840681/s23lcvp0r5auyxwy6qdq.jpg", imagable_id: 5, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840684/ofycfviw4mg2dcmdn51a.jpg", imagable_id: 5, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840687/gqwrhqgjgck6zx0psofe.jpg", imagable_id: 5, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840691/whcnvvjfu24jctljfeql.jpg", imagable_id: 5, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445840974/s2zhenkxpdzmg5kxcrw8.jpg", imagable_id: 6, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841026/bj5lyr6rzdin2fgpg38u.jpg", imagable_id: 6, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841030/x5o81egar5nbgurbk6yk.jpg", imagable_id: 6, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841037/qbobr5zhmy8blk2cycr9.jpg", imagable_id: 6, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841109/kfbvq2iu1zqq8bij2mqg.jpg", imagable_id: 6, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841111/ivjvupelatazlp23co1v.jpg", imagable_id: 6, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841446/ocsf8gluzycwfm7awova.jpg", imagable_id: 7, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841450/jtsf4cjodwgxyjzqmtsq.jpg", imagable_id: 7, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445841534/esbq1zd3k6r6ppnlgrgd.jpg", imagable_id: 7, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445842402/wge4ukmjo64b6ebcodsi.jpg", imagable_id: 8, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445842406/ai8pqkti0poozlw6uvu2.jpg", imagable_id: 8, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445842410/uuckq9u2nq6cbqkesrrj.jpg", imagable_id: 8, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445842413/lqvmbwn8ytwgujefhwop.jpg", imagable_id: 8, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843408/otqcoym5tlgny0mrmyj2.jpg", imagable_id: 9, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843412/sn5wqxqr1lva8edkgywm.jpg", imagable_id: 9, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843416/rxp5f5lp83tm0yvtbmeu.jpg", imagable_id: 9, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843680/osnrznecf7duzvp6iaem.jpg", imagable_id: 10, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843686/ynp2hx7mr3og9zrnoysy.jpg", imagable_id: 10, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843691/renukag3k8ogfsoyc5pj.jpg", imagable_id: 10, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843741/c3xnnmiabgo93mrif58w.jpg", imagable_id: 10, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843970/cb50ivbzm0wfwfexmga4.jpg", imagable_id: 11, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843972/zqtii0v1azsxrtx0a6sl.jpg", imagable_id: 11, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843978/ennj5jjdxrgupoasgroe.jpg", imagable_id: 11, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445843982/xsg1uj7i7yt7nx1ja0cw.jpg", imagable_id: 11, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445844513/oq6teau53dgaj2b36ne4.jpg", imagable_id: 12, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445844515/fxf8mbznjid6p8ynsrfb.jpg", imagable_id: 12, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445844519/rysv8apcfn02jz4egzd9.jpg", imagable_id: 12, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445844523/s0eis6m08kftsdpgsrk1.jpg", imagable_id: 12, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445844754/ctq2ydg5iuxi8ynzqouf.jpg", imagable_id: 12, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445845917/u0dinjw1n1gfdo4rd01s.jpg", imagable_id: 13, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445845922/xxdrchqw92gafyd53o39.jpg", imagable_id: 13, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445845925/b2mkgqa1gpd2ub9zdk3f.jpg", imagable_id: 13, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445845929/t0hilbjuqfjfqbubvdaj.jpg", imagable_id: 13, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445879560/ncvh0lxcs8g0bmwdlqjk.jpg", imagable_id: 14, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445879563/xkb47dkwe059kkhsjikd.jpg", imagable_id: 14, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445879584/vcgwsgtnfhziljh2drug.jpg", imagable_id: 14, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445879709/k5t0wuinufbqyi0pwggs.jpg", imagable_id: 14, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445879762/dzcu1glq0vkqirnlnt7k.jpg", imagable_id: 14, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445880465/labnndmrsuoeysmmsdti.jpg", imagable_id: 15, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445880467/egt5lbjfhshwlbovhbdf.jpg", imagable_id: 15, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445880471/f662yfncgbxdhs935n5d.jpg", imagable_id: 15, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445880476/jmfhzsuwcazileywwrbz.jpg", imagable_id: 15, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445881955/jn1nyf7x1lh3zybh5vmm.jpg", imagable_id: 16, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445881961/ayw4wlosjr1ijzraqr5k.jpg", imagable_id: 16, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445881972/rbd8tds549ndjlijkdnf.jpg", imagable_id: 16, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445881979/c6lcgeua02m9zihctk1h.jpg", imagable_id: 16, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445881985/hm9giemrqbmkom5oao07.jpg", imagable_id: 16, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445882628/obnvvfjr8k4ejxtzo4bn.jpg", imagable_id: 17, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445882632/g3txr9o8f0abtjwmjmpl.jpg", imagable_id: 17, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445882637/b0xv97jsebiiieydwyne.jpg", imagable_id: 17, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445882640/vytbmpspwipjsinuhc2y.jpg", imagable_id: 17, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883161/n1xttamwyxqtxnhja1b5.jpg", imagable_id: 18, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883167/xhlzjn2okxomxflrlxab.jpg", imagable_id: 18, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883172/jl3x6vbvheulgsicsegp.jpg", imagable_id: 18, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883180/qvdsz5zkwmo6brfeluwn.jpg", imagable_id: 18, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883186/cnqbysho7msbdfzf6qjv.jpg", imagable_id: 18, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883544/sexcikjcnlvnkhwoxtak.jpg", imagable_id: 19, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883549/ajlgo4qrrw2cl896uen8.jpg", imagable_id: 19, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883558/alyfhsv75l8qcpg7wq9y.jpg", imagable_id: 19, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445883565/qmxtmqhyye6ifcbgvaer.jpg", imagable_id: 19, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445884328/zhzsxqniqvxdmyvcjlbk.jpg", imagable_id: 20, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445884331/outske91uit6mefdslcv.jpg", imagable_id: 20, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445884334/zfajoxmiz8k3jfouvlf5.jpg", imagable_id: 20, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445884337/lkskzbfoixxbazic3vov.jpg", imagable_id: 20, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885167/f3w2ilokowd69qcnkuyr.jpg", imagable_id: 21, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885171/ederqltjzh0jtwigvyfk.jpg", imagable_id: 21, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885174/lelhlfncik9y7n6wmggp.jpg", imagable_id: 21, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885519/qs5dufff91k9y4czuxcf.jpg", imagable_id: 22, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885523/pow3ykimff95iobx6fzx.jpg", imagable_id: 22, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885527/kan5ypuqk6cad9yvhnpm.jpg", imagable_id: 22, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885776/tqxd6v0ipixlz9fdcmsf.jpg", imagable_id: 23, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885779/rsarkkc2kfu99cqqlhze.jpg", imagable_id: 23, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885782/hiam0wuibao23vb4ymii.jpg", imagable_id: 23, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445885785/ojabecbrpqsfburz4yzv.jpg", imagable_id: 23, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445886370/ep68kmj4hjek0qq6iumr.jpg", imagable_id: 24, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445886373/i2dhc3btuhsrtfwls6w0.jpg", imagable_id: 24, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445886376/zhgn0tszcefabqgohl0c.jpg", imagable_id: 24, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445886379/kwfvwo0hxzsyfirayvpe.jpg", imagable_id: 24, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445887870/lfz6qlczizwdtr3n7h9a.jpg", imagable_id: 25, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445887873/gxcq8fkgnw4lfk1u3muh.jpg", imagable_id: 25, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445887876/cqu3lspcp5bso71iezd0.jpg", imagable_id: 25, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445888326/ijvvzexmkdllhrguohnt.jpg", imagable_id: 26, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445888330/tet9zgcrjsgwcwan8e27.jpg", imagable_id: 26, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445888334/eevcyrajiuqod8c3atpx.jpg", imagable_id: 26, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445888997/zjhglm5q5rvh6bhmjktb.jpg", imagable_id: 27, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445889012/paz4zcqgd9iujnahw0f9.jpg", imagable_id: 27, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445889023/trflgdmr3rvsmpghno95.jpg", imagable_id: 27, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445889037/ypl91l4v4g2yczk95gcy.jpg", imagable_id: 27, imagable_type: "Adventure"},
  {image_url: "http://res.cloudinary.com/climb-california/image/upload/v1445889050/gduzoa5r3khemt8sqfak.jpg", imagable_id: 27, imagable_type: "Adventure"}
].each do |image| 
  i = Image.new(image)
  i.save(validate: false)
end

List.create!([
  {title: "East Side Bouldering", description: nil, user_id: 1},
  {title: "High Sierra Mountains", description: nil, user_id: 1},
  {title: "Southern California Bouldering", description: nil, user_id: 2},
  {title: "Socal Sport Climbing", description: nil, user_id: 4},
  {title: "Santa Monica Climbing", description: nil, user_id: 8},
  {title: "Sport Areas to Check Out", description: nil, user_id: 8},
  {title: "Yosemite Climbing", description: nil, user_id: 6},
  {title: "High Sierra Climbing", description: nil, user_id: 6},
  {title: "California Trad", description: nil, user_id: 5},
  {title: "Trad Areas", description: nil, user_id: 1},
  {title: "Bay Area Bouldering", description: nil, user_id: 2}
])
Review.create!([
  {content: "Such a gorgeous area to camp. The bouldering here is world class and a bit scary...", rating: 5, adventure_id: 1, user_id: 3},
  {content: "This place is great in the fall, but the crowds in the summer can get a bit too big. I have to wait in line for most of the easy climbs and the  swimming hole gets gross later in the summer. Go in the fall! ", rating: 4, adventure_id: 12, user_id: 3},
  {content: "All the climbing is just a 5 min walk from camp. It's the best of everything and the climbing is also a lot of fun! ", rating: 5, adventure_id: 11, user_id: 3},
  {content: "Props to soloing this, but I think you're crazy... ", rating: 2, adventure_id: 4, user_id: 3},
  {content: "The climbing here is fun, but the hike in is HELL. It's 45 min of straight uphill. Make sure you are in shape. ", rating: 4, adventure_id: 20, user_id: 3},
  {content: "I don't know why you'd go here to boulder. The roped climbing here is so much better than the bouldering. But going here for a weekend trip takes a lot of planning since camping is so hard to find. Still, world class. One of the most gorgeous areas in California. ", rating: 5, adventure_id: 7, user_id: 3},
  {content: "One of the most magical places! Such isolation and remoteness make this a must visit place. ", rating: 5, adventure_id: 18, user_id: 1},
  {content: "What a great trip! The cross country hiking to the crest is fantastic and fun and the climbing is great. We free soloed most of the crest! ", rating: 5, adventure_id: 16, user_id: 1},
  {content: "Definitely the best sport climbing in California. The place has it all and there's even free camping right by the gorge! Don't forget to checkout Eldorado Roof if you go here. It's stunning. ", rating: 5, adventure_id: 27, user_id: 1},
  {content: "While the climbing is fun, the place is a mess. People dump all sorts of junk here and the view is not great. I think it's the kind of place for a quick weekend outing at best. ", rating: 3, adventure_id: 9, user_id: 1},
  {content: "Beautiful bouldering in a high alpine setting. Aside from Bishop, I think this is one of the best areas in California to boulder. ", rating: 5, adventure_id: 8, user_id: 1},
  {content: "The bouldering here is sharp! You will wreck your skin after just one day, but it's so worth it. Best bouldering in California hands down. ", rating: 5, adventure_id: 1, user_id: 2},
  {content: "The bouldering here is fun but HARD. Your ego will be shattered if you think you can climb the same grades here as anywhere else around. ", rating: 4, adventure_id: 7, user_id: 2},
  {content: "This place is the best in the state for trad climbing! It's magical and the climbing is endless. By far my go to place each winter. ", rating: 5, adventure_id: 19, user_id: 6},
  {content: "So cool! Props on soloing this. That takes guts. I need to follow in your footsteps now. ", rating: 5, adventure_id: 4, user_id: 6}
])
User.create!([
  {id: 1, name: "Justin Menestrina", email: "user@example.com", password_digest: "$2a$10$K3HEBoshNWW5qMlAJ6Y31.FPep4miqbOC.3D8xsdctJMURFg/qn1a", session_token: "iKdveqLXTxmG_nuMlSycQQ", location: "San Francisco, CA", lat: 37.7833, lng: -122.4167},
  {id: 2, name: "Bailey Schmidt", email: "bailey@example.com", password_digest: "$2a$10$jqZ6ICaWjS0.H2jih.ZzOOAFO1dgroVXRWgRh4Nigu.Ee5pZwDvSu", session_token: "Tz7EtlSi3cyLfmujqP3anw", location: "Los Angeles", lat: 34.0522342, lng: -118.2436849},
  {id: 3, name: "Kristen Fujii", email: "kristen@example.com", password_digest: "$2a$10$QY8pPJW5N0C2TaPcRnBPOe4rfGOl/MFkRcheWldhY6dvxhbZ8T8Ge", session_token: "N8YlrZwXnLqBe-sQjf0vEg", location: "Los Angeles", lat: 34.0522342, lng: -118.2436849},
  {id: 4, name: "Alisha Tran", email: "alisha@example.com", password_digest: "$2a$10$P9v/IgLbbOaj4IVuSIaRO.ZDeOG0cecFLUQXQ2IefKS7j44T0jK9i", session_token: "vcEvik0N_HcuPBEFDCGrcw", location: "Torrance", lat: 33.8358492, lng: -118.3406288},
  {id: 5, name: "Chris Ververis ", email: "chris@example.com", password_digest: "$2a$10$lTT06tM9aQKuwmitnavYr.D1Cjre6IVsQd6KqHi0MuXs/YNhDHRJy", session_token: "l-HnsdZL1zDrgy7CjBUJnQ", location: "Bishop", lat: 37.3614238, lng: -118.3996636},
  {id: 6, name: "Brad Moore", email: "brad@example.com", password_digest: "$2a$10$i0..WD1Kf8z79sdEPRq3Pe3.cIB5rZlq5YY9c5E/f9dBzl.LNezby", session_token: "o66i5LjRQDQVtsUF8fTRYg", location: "Yosemite Valley", lat: 37.7455701, lng: -119.5936038},
  {id: 7, name: "Nic Canac", email: "nic@example.com", password_digest: "$2a$10$QIogmtvcDL3AVTvPh84yCOiz6eU/Fszb3ZbIjBcuEZvxqN2zsigmy", session_token: "I6cnEtI_z12ftc2TuXohCQ", location: "Tahoe City", lat: 39.1446803, lng: -120.1762494},
  {id: 8, name: "Hannah Hayes", email: "hannah@example.com", password_digest: "$2a$10$a9NS5dv1Vd6NBIofvSu/I.LSazSQsZ7N4WI6lWJWuQl4AZlb61.Dy", session_token: "CQNIZ_RJUy6a0bR1S9GdiA", location: "Berkeley", lat: 37.8715926, lng: -122.272747}
])
